### ISSUE TITLE
Statistics from Google Analytics on CKAN 2.2

### ISSUE THREAD

**Issue by ykhadilkar-rei** [ckan/ckanext-googleanalytics#11]
Does statistics retrieval work on CKAN 2.2?  In documentation it says "CKAN 1.X only". What would it take to support statistic retrieval on CKAN 2.2?

**Comment by badbruce07** [comment]
same thing I've been wondering too. Don't know why CKAN can't be up to date

**Comment by camfindlay** [comment]
Has anyone installed and got evidence this doesn't work on CKAN >1.x? Perhaps it's a docs localised bug ;)

**Comment by smotornyuk** [comment]
Yeah, it was working with CKAN2.x previously and definitely WILL after #26
