### ISSUE TITLE
Google password?

### ISSUE THREAD

**Issue by Vanuan** [ckan/ckanext-googleanalytics#15]
Why it requires google password? Google analytics doesn't require providing google password to track page views.

**Comment by Vanuan** [comment]
There's access token and refresh token available:
https://developers.google.com/identity/protocols/OAuth2ForDevices

**Comment by camfindlay** [comment]
I think the password is required for it to pull tracking data back into CKAN.

You could also generate a 1 time password unique to the CKAN installation your using. Also given you set it in your environment configuration (not stored in a database or anything particularly migratable) which is outside of webroot exposure would only be to those with sysadmin access anyway presumably?

Still, OAuth token are I nice way to manage this type of thing. @Vanuan would you be interested in having a crack at re-implementing this to make use of tokens?

**Comment by smotornyuk** [comment]
@Vanuan , how about #26 - do you think that this solution solves the issue?

**Comment by Vanuan** [comment]
Yeah, I would think that Google service account allows to keep personal google account password secret.
