### ISSUE TITLE
Extension broken by discontinuation of version 2.3 of Analytics API

### ISSUE THREAD

**Issue by augusto-herrmann** [ckan/ckanext-googleanalytics#2]
With the discontinuation of version 2.3 of the Google Analytics API by Google, this extension became broken. This has been reported on the CKAN Dev mailing list a couple of months ago, but apparently no one is working on a fix yet.

http://lists.okfn.org/pipermail/ckan-dev/2012-August/003016.html
http://lists.okfn.org/pipermail/ckan-dev/2012-October/003242.html

This extension needs to be updated to support the new version of the Analytics API. A migration guide is available from Google to help someone interested in doing that:

https://developers.google.com/analytics/resources/articles/gdata-migration-guide

**Comment by gjlawran** [comment]
Would recommend closing this issue @rossjones  code resolves this issue.

**Comment by rossjones** [comment]
Thanks.
