### ISSUE TITLE
Extension adds "?_ga=..." parameters to all external links

### ISSUE THREAD

**Issue by jakubklimek** [ckan/ckanext-googleanalytics#30]
When googleanalytics is enabled in CKAN 2.6.1 (not tested with other versions), it adds parameters like ```?_ga=1.259127497.2133035748.1425991248``` to all outgoing external links (like in the footer) on mouse up event. It does not do this for links that go back to the same instance (like to datasets or organizations).

If the target of the external link processes HTTP GET parameters, it gets confused by this. I have not found a switch to turn this off.

**Comment by gleb-rudenko** [comment]
I'll take a look at it

**Comment by jakubklimek** [comment]
Seems working OK after the patch. Should be closed?

**Comment by smotornyuk** [comment]
Thanks. Same for me, just wanted to receive someone's other verification:)
