### ISSUE TITLE
Events not being logged under CKAN 2.0

### ISSUE THREAD

**Issue by darwinp** [ckan/ckanext-googleanalytics#4]
Viewing stats for CKAN 2.0 sites it would appear that no events are being logged by Google Analytics. This means that no data is available for resource downloads etc.

**Comment by camfindlay** [comment]
@darwinp does https://github.com/ckan/ckan/pull/827 fix the issue you raised ages ago? Perhaps this issue can be closed?

**Comment by smotornyuk** [comment]
I checked this one and it definitely was fixed. Issue closed
