### ISSUE TITLE
[Question] Does the plugin support retrieving access information of CKAN API in CKAN >2.7

### ISSUE THREAD

**Issue by waue0920** [ckan/ckanext-googleanalytics#42]
After I add-on the plugin in my CKAN (v2.7), it can correctly show user accessing ckan website behavior in google analytics platform. 
But I also need to collect the statistics information of user's access behaviors by "ckan api" or "tool" (ie: wget) without through ckan web site, does the plugin support it ( ckan >2.7) ?

**Comment by smotornyuk** [comment]
Yes, CKAN v2.8 and support of upcomming CKAN v2.9 is in experimental state and available inside `py3` branch
