### ISSUE TITLE
Broken compatibility with python 2.7

### ISSUE THREAD

**Issue by ccancellieri** [ckan/ckanext-googleanalytics#66]
Hi guys,
 looks like it's impossible to install this plugin (from master branch) over python 2.7:
 
 bash-5.1# python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    with open(os.path.join(HERE, 'README.md'), encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function

The above open(..., encoding) looks not supported on python2.7
This is my last working upgrade: 3e620b574a9d75bfd5d88740cbf84d1ebe3172f9

**Comment by frafra** [comment]
Similar issue: https://github.com/ckan/ckan/pull/6532

**Comment by Zharktas** [comment]
This extensions would benefit from CI integration like some other extensions have, those catch most of the errors.

**Comment by smotornyuk** [comment]
I've added py2 compatible `open[encoding]`
